/************************************************

collisions.h - contains frontend for evaluating the collision operator. 

Requires weights generated by weights.h

Requires linking of conserve.h

Requires linking of momentRoutines.h

**************************************************/

#ifndef _COLLISIONS_GPU_H
#define _COLLISIONS_GPU_H
#include <fftw3.h>

/*********************
function dealloc_coll
deallocates all dynamically allocated memory for the collisions module
 ********************/

static void fft3D_cuda(const fftw_complex *in, fftw_complex *out, fftw_complex *temp, const fftw_plan p, const double delta, const double L_start, const double L_end, const double sign, const double *var, const double *wtN, const double scaling, int invert);

#endif
